{
  "profile": {
    "packages": [
      "python",
      "nodejs",
      "java-openjdk",
      "rust",
      "bluez",
      "bluez-utils",
      "networkmanager",
      "networkmanager-ssh",
      "networkmanager-ssh-gnome",
      "wpa_supplicant",
      "yay",
      "pamac",
      "wget",
      "cargo",
      "zsh",
      "tree",
      "tmux",
      "rsync",
      "vlc",
      "gparted",
      "rclone-browser",
      "code",
      "gnome",
      "gnome-tweaks",
      "git",
      "rclone",
      "gnome-keyring",
      "gnome-screenshot",
      "dialog",
      "efibootmgr",
      "linux-firmware",
      "hyprland"
    ]
  },
  "user": {
    "username": "your_username",
    "password": "your_password",
    "groups": ["wheel"]
  },
  "disk": {
    "device": "/dev/sda",
    "partition_table_type": "gpt",
    "boot_partition_size": 512,
    "swap_partition_size": 2048
  },
  "network": {
    "hostname": "your_hostname",
    "timezone": "Europe/Paris",
    "dhcp": true
  },
  "services": {
    "enabled": [
      "NetworkManager",
      "sshd"
    ]
  },
  "post_installation": {
    "commands": [
      "echo \"Your post-installation commands here\""
    ]
  }
}
